### ISSUE TITLE
Cannot install redis [docker] Breaking Gitdox

### ISSUE THREAD

**Issue by akashkroy** [gucorpling/gitdox#161]
Running dockerized Gitdox

On Browser: I am getting a `Internal Server Error`
Checked Apache error.log file inside the container. 
```
Traceback (most recent call last):
  File "/var/www/html/editor.py", line 22, in <module>
    import modules.redis_cache as cache
  File "/var/www/html/modules/redis_cache.py", line 3, in <module>
    import redis
ImportError: No module named redis
```

Tried installing redis: 
```
Collecting redis
  Using cached https://files.pythonhosted.org/packages/9d/9c/547d9846679a6faa6478d3ce7e0326642fef47436d6a9cfa09f689d16e25/redis-4.1.0.tar.gz
Collecting deprecated>=1.2.3 (from redis)
  Using cached https://files.pythonhosted.org/packages/51/6a/c3a0408646408f7283b7bc550c30a32cc791181ec4618592eec13e066ce3/Deprecated-1.2.13-py2.py3-none-any.whl
Collecting packaging>=21.3 (from redis)
  Using cached https://files.pythonhosted.org/packages/df/9e/d1a7217f69310c1db8fdf8ab396229f55a699ce34a203691794c5d1cad0c/packaging-21.3.tar.gz
Collecting importlib-metadata>=1.0; python_version < "3.8" (from redis)
  Using cached https://files.pythonhosted.org/packages/50/05/fef7fbb7e781e0632ebba4e6e37bcc88b9615e76338850dc31435091ddc0/importlib_metadata-4.10.0.tar.gz
  Running setup.py (path:/tmp/pip-build-WZ9rZf/importlib-metadata/setup.py) egg_info for package importlib-metadata produced metadata for project name unknown. Fix your #egg=importlib-metadata fragments.
Collecting wrapt<2,>=1.10 (from deprecated>=1.2.3->redis)
  Using cached https://files.pythonhosted.org/packages/3b/e8/702ff292e05c8d74c6babde2266f6f62acc0d851784081c6aca5dff8a455/wrapt-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyparsing!=3.0.5,>=2.0.2 (from packaging>=21.3->redis)
  Using cached https://files.pythonhosted.org/packages/ab/61/1a1613e3dcca483a7aa9d446cb4614e6425eb853b90db131c305bd9674cb/pyparsing-3.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WZ9rZf/pyparsing/setup.py", line 8, in <module>
        from pyparsing import __version__ as pyparsing_version
      File "/tmp/pip-build-WZ9rZf/pyparsing/pyparsing/__init__.py", line 100
        major: int
             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WZ9rZf/pyparsing/
You are using pip version 8.1.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Pyparsing is not supporting Python 2.7 I guess. 

Maybe upgrade the code to Python3 ?

**Comment by amir-zeldes** [comment]
This is strange - the docker container should get its own actual redis backend:

https://github.com/gucorpling/gitdox/blob/dev/Dockerfile#L6

And the requirements contain the python API for communicating with it:

https://github.com/gucorpling/gitdox/blob/dev/requirements.txt#L7

As long as you're running it in docker, you shouldn't have to worry about the Python version. The docker file was added by @lgessler - do you have any insights on this error?

**Comment by lgessler** [comment]
@akashkroy I don't encounter this error when I run the following:

```
docker run -dit --restart unless-stopped --name gitdox -p 80:80 gucorpling/gitdox gitdox
```

Can you please share more about how to reproduce this issue?

**Comment by akashkroy** [comment]
Okay so I followed the instructions in the readme.md 
```
sudo git clone https://github.com/gucorpling/gitdox /var/www/gitdox
sudo chown -R www-data:www-data /var/www/gitdox
docker run -dit --restart unless-stopped --name gitdox -v /var/www/gitdox:/var/www/html -p 80:80 gucorpling/gitdox gitdox
```
Using  the git repo as a volume bind mount throws the above error. 
The command that @lgessler  mentioned above works.

**Comment by amir-zeldes** [comment]
OK, great, glad to hear it's working - thanks @lgessler !
